config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users

  resources :activities
  resources :comments

  resources :users, only: [:index, :show]

  get '/profile', to: 'users#profile', as: :profile

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	has_many:comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :activity
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :activities
	has_many :comments
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	before_action :find_activity, only: [:show, :edit, :update, :destroy]
  def index
  	@activity = Activity.all
  end

  def show
  end

  def edit
  end

  def create
  	@activity = Activity.new(user_params)

	  if @activity.save
	    redirect_to @activity
	  else
	    render 'new'
	  end
	end

	def new
		@activity = Activity.new
	end

	def update
    if @activity.update(article_params)
	    redirect_to @activity
	  else
	    render 'edit'
	  end
	end

	def destroy
		@activity.destroy method: :delete

		redirect_to users_path
	end

  private

  def user_params
  	params.require(:activity).permit(:first_name, :last_name, :description)
  end

  def find_activity
  	@activity = Activity.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :first_name
      devise_parameter_sanitizer.for(:sign_up) << :last_name
      devise_parameter_sanitizer.for(:sign_up) << :description  
      devise_parameter_sanitizer.for(:account_update) << :first_name
      devise_parameter_sanitizer.for(:account_update) << :last_name
      devise_parameter_sanitizer.for(:account_update) << :description 
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  	@comments = Comment.all
  end

  def show
  	@comment = Comment.find(params[:id])
  end

  def edit
  	@comment = Comment.find(params[:id])
  end

  def create
  	@comment = Comment.new(user_params)

	  if @comment.save
	    redirect_to @comment
	  else
	    render 'new'
	  end
	end

	def new
		@comment = Comment.new
	end

	def update
	  @comment = Comment.find(params[:id])
 
	  if @comment.update(article_params)
	    redirect_to @comment
	  else
	    render 'edit'
	  end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy method: :delete

		redirect_to users_path
	end

  private

  def user_params
  	params.require(:comment).permit(:first_name, :last_name, :description)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.haml
activities index.html.haml
.center


  %h2 Activites
  %ul
    %li
      %h4
        - @activity.each do |f|
          %li
            = f.title.capitalize
          %li
            = f.category.capitalize
          %li
            = f.description.capitalize
          %hr
        -# = @activity.first.title
        -# = @activity.title.capitalize
        -# = @activity.category.capitalize
        -# = @activity.description.capitalize

  %h2 Your Bucket List
  %ul
    / - for 

app/views/activities/new.html.haml
/ = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
/   = devise_error_messages! 
/ .col.s6
/   %label{:for => "exampleInputName1"} First Name
/   = f.text_field :first_name, placeholder: 'First Name', class: 'formcontrol'
/ .col.s6
/   %label{:for => "exampleInputUsername1"} Last Name
/   = f.text_field :last_name, placeholder: 'Last Name', class: 'formcontrol'
/ Date of Birth
/ %input.datepicker{:type => "date"}
/ %br
/ %br
/ %i.material-icons.prefix mode_edit
/ About You
/ = f.text_field :description, placeholder: 'Description', class: 'materialize-textarea'
/ %label{:for => "icon_prefix2"}  
/ .form-group
/ %label{:for => "exampleInputFile"} Import a Profile Picture
/ %input#exampleInputFile{:type => "file"} 
/ %label
/ %br
/ %br

app/views/layouts/_navbar.html.haml
.navbar-fixed
  %nav.brown.darken-2.z-depth-2
    .nav-wrapper
      %a.brand-logo{:href => root_path} Bucket List
      %a.button-collapse{"data-activates" => "mobile-demo", :href => "#"}
        %i.material-icons menu
      %ul.right.hide-on-med-and-down
        - if user_signed_in?  
          %li
            = link_to 'Home', root_path 
          %li
            = link_to 'Users', users_path        
          %li
            = link_to 'Activities',activities_path  
          %li
            %a.dropdown-button{"data-activates" => "dropdown1", :href => "#"}Your Profile
            %ul#dropdown1.dropdown-content
              %li
                = link_to 'Show Profile', profile_path #TODO fix path
              %li.divide
              %li
                =link_to 'Update Profile', edit_user_registration_path
          %li
            = link_to('Sign Out', destroy_user_session_path, :method => :delete)
        - else
          %li
            = link_to('Login', new_user_session_path)

      %ul#mobile-demo.side-nav  
        - if user_signed_in?  
          %li
            = link_to 'Home', root_path 
          %li
            = link_to 'Users', users_path 
          %li
            = link_to 'Activities', activities_path
          %li
            = link_to 'Show Profile', profile_path
          %li
            =link_to 'Update Profile', edit_user_registration_path     
          %li
            = link_to('Sign Out', destroy_user_session_path, :method => :delete)
        - else
          %li
            = link_to('Login', new_user_session_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BucketList

    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{rel:"stylesheet", href:"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css"}
    %script{src:"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"}
          

  %body
    %script{:async => "async", :src => "//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-560b1c5e0934f3da"}
    = render 'layouts/navbar'
    .container
      = yield

app/views/static_pages/home.html.haml
home

app/views/users/edit_profile.html.haml
%br
%br 
%br
%form
  .row
    .form-group.col.s6
      %label{:for => "first_name"} First Name
      %input#exampleInputName1.formcontrol{:placeholder => "First Name", :type => "text"}
    .form-group.col.s6
      %label{:for => "last_name"} Last Name
      %input#exampleInputUsername1.formcontrol{:placeholder => "Last Name", :type => "text"}  
    Date of Birth
    %input.datepicker{:type => "date"}
    %br
    %br
    %i.material-icons.prefix mode_edit
    About You
    %textarea#icon_prefix2.materialize-textarea
    %label{:for => "icon_prefix2"}  
  .form-group
    %label{:for => "profile_picture"} Import a Profile Picture
    %input#exampleInputFile{:type => "file"} 
    %label
    %br
    %br
  %button.btn.btn-default{:type => "submit"} Update
  %br
  %br
  %br
  %br

app/views/users/index.html.haml
.center
  %h2 Users
  %hr
  %ul
    %li
      %h4
        - @user.each do |f|
          %li
            = f.first_name.capitalize
            = f.last_name.capitalize
          %li
            = f.description.capitalize

app/views/users/profile.html.haml
%br
%br
%br
%br
%br
%br
%br
%br
%br
%br
%br
%br
%h4.center-align  
  = current_user.first_name  
  = current_user.last_name 
%br
%h5.center-align  
  = current_user.description 
%br
%h4.center-align
  Bucketlist Items :
  %br
  %br
  %br
%h4  
.center-align
  %h5{:href => "#"} 
  = link_to 'Add Activity', new_activity_path
  %h5{:href => "#"} 
  = link_to 'Remove an Activity', new_activity_path
%br
%br
%br
%br

app/views/users/show.html.haml
SINGLE USER SHOW PAGE